duid
vendorclassid
# persistent
option static_routes, classless_static_routes
option interface_mtu
nooption host_name
require dhcp_server_identifier
slaac private
noipv4ll
noipv6
noarp
nohook resolv.conf
denyinterfaces wlan* eth*

interface eno1
static ip_address=192.168.1.190/24
static routers=192.168.1.1
