# [env]
# TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
bold = { family = "JetBrainsMono Nerd Font", style = "SemiBold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Medium" }
size = 18
offset = { x = -1, y = 3 }

[mouse]
hide_when_typing = true

[window]
dynamic_padding = true
decorations = "none"
padding = { x = 5, y = 5 }

[colors.primary]
background = "0x1f2329"
foreground = "0xabb2bf"

[colors.normal]
black = "0x1e2127"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0x828791"

[colors.bright]
black = "0x5c6370"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0xe6efff"

[colors.dim]
black = "0x1e2127"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0x828791"
