local Remap = require("jedi.keymap")
local nnoremap = Remap.nnoremap

nnoremap("<leader>ss", function()
    require('telescope.builtin').grep_string({ search = vim.fn.input("Grep For > ")})
end)
nnoremap("<leader>F", function()
    require('telescope.builtin').git_files()
end)
nnoremap("<leader>f", function()
    require('telescope.builtin').find_files()
end)

nnoremap("<leader>sw", function()
    require('telescope.builtin').grep_string { search = vim.fn.expand("<cword>") }
end)
nnoremap("<leader>sb", function()
    require('telescope.builtin').buffers()
end)
nnoremap("<leader>sh", function()
    require('telescope.builtin').help_tags()
end)

nnoremap("<leader>src", function()
    require('jedi.telescope').search_dotfiles({ hidden = true })
end)
-- nnoremap("<leader>va", function()
    -- require('theprimeagen.telescope').anime_selector()
-- end)
-- nnoremap("<leader>vc", function()
    -- require('theprimeagen.telescope').chat_selector()
-- end)
nnoremap("<leader>gc", function()
    require('jedi.telescope').git_branches()
end)
nnoremap("<leader>gw", function()
    require('telescope').extensions.git_worktree.git_worktrees()
end)
nnoremap("<leader>gm", function()
    require('telescope').extensions.git_worktree.create_git_worktree()
end)
nnoremap("<leader>td", function()
    require('jedi.telescope').dev()
end)
